    create table _group (
        department_id bigint,
        id bigint generated by default as identity,
        name varchar(255),
        size varchar(255) check (size in ('MEDIUM','LARGE')),
        primary key (id)
    );

    create table _user (
        is_account_non_expired boolean not null,
        is_account_non_locked boolean not null,
        is_credentials_non_expired boolean not null,
        is_email_verified boolean not null,
        is_enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        verification_expiration timestamp(6),
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255),
        provider varchar(255) check (provider in ('GOOGLE')),
        role varchar(255) check (role in ('VIEWER','CREATOR','ADMIN')),
        verification_code varchar(255),
        primary key (id)
    );

    create table course (
        credits integer,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table department (
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table forgot_password (
        expiration_time timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null unique,
        verification_code varchar(255) not null,
        primary key (id)
    );

    create table refresh_token (
        expiration_time timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint unique,
        refresh_token varchar(255) not null unique,
        primary key (id)
    );

    create table room (
        id bigint generated by default as identity,
        room_num varchar(255) not null,
        size varchar(255) check (size in ('MEDIUM','LARGE')),
        type varchar(255) check (type in ('CLASSROOM','LAB')),
        primary key (id)
    );

    create table schedule_item (
        day smallint not null check (day between 0 and 6),
        id bigint generated by default as identity,
        room_id bigint,
        setup_id bigint,
        teaching_mode varchar(255) check (teaching_mode in ('ONLINE','CLASSROOM')),
        primary key (id)
    );

    create table schedule_item_time_slots (
        schedule_item_id bigint not null,
        time_slot_id bigint not null
    );

    create table schedule_lunch_item (
        group_id bigint not null,
        id bigint generated by default as identity,
        day varchar(255) check (day in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
        primary key (id)
    );

    create table schedule_lunch_item_time_slots (
        schedule_lunch_item_id bigint not null,
        time_slot_id bigint not null
    );

    create table schedule_shared_item (
        day smallint not null check (day between 0 and 6),
        id bigint generated by default as identity,
        room_id bigint,
        setup_shared_id bigint,
        teaching_mode varchar(255) check (teaching_mode in ('ONLINE','CLASSROOM')),
        primary key (id)
    );

    create table schedule_shared_item_time_slots (
        schedule_shared_item_id bigint not null,
        time_slot_id bigint not null
    );

    create table setupItem (
        hours_a_week integer,
        hours_in_lab integer,
        course_id bigint,
        group_id bigint,
        id bigint generated by default as identity,
        teacher_id bigint,
        course_priority varchar(255) check (course_priority in ('BEFORE_LUNCH','AFTER_LUNCH')),
        preferred_room_type varchar(255) check (preferred_room_type in ('CLASSROOM','LAB')),
        primary key (id)
    );

    create table setup_shared (
        hours_in_lab integer,
        course_id bigint,
        id bigint generated by default as identity,
        set_id bigint,
        teacher_id bigint,
        course_priority varchar(255) check (course_priority in ('BEFORE_LUNCH','AFTER_LUNCH')),
        preferred_room_type varchar(255) check (preferred_room_type in ('CLASSROOM','LAB')),
        primary key (id)
    );

    create table setup_shared_groups (
        group_id bigint not null,
        setup_shared_id bigint not null
    );

    create table setup_shared_set (
        hours_a_week integer,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table teacher (
        daily_hours integer,
        weekly_hours integer,
        id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table time_slot (
        end_time time(6) not null,
        start_time time(6) not null,
        id bigint generated by default as identity,
        primary key (id)
    );

    alter table if exists _group 
       add constraint FK33cmix2ni6t0qtit9g5w2lk8m 
       foreign key (department_id) 
       references department;

    alter table if exists forgot_password 
       add constraint FKdwoehj9t9lscckgl6j44hy9ug 
       foreign key (user_id) 
       references _user;

    alter table if exists refresh_token 
       add constraint FKbws85up72jgwebb6ttkjiytg3 
       foreign key (user_id) 
       references _user;

    alter table if exists schedule_item 
       add constraint FKjg012k4lb1iohmtpgiqo6492x 
       foreign key (room_id) 
       references room;

    alter table if exists schedule_item 
       add constraint FKot6y8b6k7twu73s0km1ca8wi1 
       foreign key (setup_id) 
       references setupItem;

    alter table if exists schedule_item_time_slots 
       add constraint FKleq5wxqnnh0m6y54jp3kg91tg 
       foreign key (time_slot_id) 
       references time_slot;

    alter table if exists schedule_item_time_slots 
       add constraint FKowy32tdj03v8sb1jx18egyh99 
       foreign key (schedule_item_id) 
       references schedule_item;

    alter table if exists schedule_lunch_item 
       add constraint FKahpf7ho0f0csmyx3b5k958ga6 
       foreign key (group_id) 
       references _group;

    alter table if exists schedule_lunch_item_time_slots 
       add constraint FKriitengqx121l90p4c957vwha 
       foreign key (time_slot_id) 
       references time_slot;

    alter table if exists schedule_lunch_item_time_slots 
       add constraint FK2vnkojw1111o6ny9u7m16o8vc 
       foreign key (schedule_lunch_item_id) 
       references schedule_lunch_item;

    alter table if exists schedule_shared_item 
       add constraint FKs93lfwrhdkautpfpmo4t54p08 
       foreign key (room_id) 
       references room;

    alter table if exists schedule_shared_item 
       add constraint FK7y0vgdoi3hilv1k98aerq653k 
       foreign key (setup_shared_id) 
       references setup_shared;

    alter table if exists schedule_shared_item_time_slots 
       add constraint FK2tm13vj4pex475o6xh1rgtex4 
       foreign key (time_slot_id) 
       references time_slot;

    alter table if exists schedule_shared_item_time_slots 
       add constraint FKio6k387ii7hk5t6r5x5iad2x0 
       foreign key (schedule_shared_item_id) 
       references schedule_shared_item;

    alter table if exists setupItem
       add constraint FKey3t6h75g71t8a36meu4amf32 
       foreign key (course_id) 
       references course;

    alter table if exists setupItem
       add constraint FK9lp0q3mkx6wxfwtmbn2y12atl 
       foreign key (group_id) 
       references _group;

    alter table if exists setupItem
       add constraint FKq4t2k2olp7st9yhwnyxm12w20 
       foreign key (teacher_id) 
       references teacher;

    alter table if exists setup_shared 
       add constraint FKe52onovgbrmawhe1rg1osnd0i 
       foreign key (course_id) 
       references course;

    alter table if exists setup_shared 
       add constraint FKsrrwvq5p5o766hrn88gmtltcw 
       foreign key (set_id) 
       references setup_shared_set;

    alter table if exists setup_shared 
       add constraint FK1f9bb92tctqapw7j0rtgjne5u 
       foreign key (teacher_id) 
       references teacher;

    alter table if exists setup_shared_groups 
       add constraint FKdj6d9at5hq2pp1abjjvlgyrbv 
       foreign key (group_id) 
       references _group;

    alter table if exists setup_shared_groups 
       add constraint FK70bh1onfqpt6yr6fdbibeyk1e 
       foreign key (setup_shared_id) 
       references setup_shared;
