jwt:
  secret: 2jZA6EAK3oiiMtlYc7EPaGIqbeWFbn0v8yRYTsqgRbo=
spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: ddl.sql

  application:
    name: schedule_composer
  jackson:
    time-format: HH:mm
  mail:
    host: smtp.gmail.com
    port: 587
    username: "schedulecomposerapp@gmail.com"
    password: "zwrr qyyb seei javu"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            provider: google
#            client-id: 147094010419-8nabfgrhe7tc3n4udlhrvrenthfskm4a.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile, email
  profiles:
    active: prod

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html



---
# Dev profile
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:~/tes
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


---
# Prod profile
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_composer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
    show-sql: true
