spring:
  application:
    name:
      schedule_composer
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_composer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
springdoc:
  api-docs:
    path: /api-docs