spring:
  application:
    name: schedule_composer
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_composer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-format: HH:mm
  mail:
    host: smtp.gmail.com
    port: 587
    username: "schedulecomposerapp@gmail.com"
    password: "zwrr qyyb seei javu"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true


jwt:
  secret: 2jZA6EAK3oiiMtlYc7EPaGIqbeWFbn0v8yRYTsqgRbo=



#spring:
#  application:
#    name: schedule_composer
#  datasource:
#    url: jdbc:h2:~/tes
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#
#  h2:
#    console:
#      enabled: true
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  sql:
#    init:
#      platform: h2
#      mode: never
#
#springdoc:
#  api-docs:
#    path: /api-docs
#    enabled: true
#  swagger-ui:
#    enabled: true