jwt:
  secret: 2jZA6EAK3oiiMtlYc7EPaGIqbeWFbn0v8yRYTsqgRbo=
spring:
  application:
    name: schedule_composer
  datasource:
    url: jdbc:postgresql://localhost:5432/schedule_composer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    time-format: HH:mm
  mail:
    host: smtp.gmail.com
    port: 587
    username: "schedulecomposerapp@gmail.com"
    password: "zwrr qyyb seei javu"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 147094010419-8nabfgrhe7tc3n4udlhrvrenthfskm4a.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          github:
            client-id: Ov23li2hRairLeiMUcX0
            client-secret: e0890ca26dea10b105f819da041957133662e648
            scope: read:user,user:email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs





#spring:

#  datasource:
#    url: jdbc:h2:~/tes
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  sql:
#    init:
#      platform: h2
#      mode: never
#