name: Deploy App

on:
  workflow_dispatch:
  push:
    branches:
      - cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set Variables
        run: |
          echo "IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/schedule_composer_backend:${{ github.sha }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set output variable
        id: set_output 
        run: echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/docker-compose.yml"

      - name: Deploy on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_IMAGE=${{ needs.build.set_output.IMAGE_NAME }}
            docker-compose down
            docker-compose up -d --build
